"""empty message

Revision ID: 3bf78cc20320
Revises: 47134be45986
Create Date: 2023-02-14 18:20:34.130260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf78cc20320'
down_revision = '47134be45986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_employee')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('employees_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employees_company_id_fkey', 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    op.create_table('company_employee',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='company_employee_company_id_fkey'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='company_employee_employee_id_fkey')
    )
    # ### end Alembic commands ###
