"""empty message

Revision ID: 577b02e188aa
Revises: 1e423566a4ae
Create Date: 2023-02-08 15:41:28.324921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577b02e188aa'
down_revision = '1e423566a4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
