"""empty message

Revision ID: af2a33ad2456
Revises: 3bf78cc20320
Create Date: 2023-02-14 19:46:11.366193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2a33ad2456'
down_revision = '3bf78cc20320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('employees_email_key', type_='unique')
        batch_op.drop_constraint('employees_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint('employees_phone_key', ['phone'])
        batch_op.create_unique_constraint('employees_email_key', ['email'])

    # ### end Alembic commands ###
